/* GENERATED by tools/derive-screenshots.mjs — do not edit by hand. */

export type ScreenshotMeta = { w: number; h: number; widths: number[] };

/** Intrinsic size and available WebP widths, keyed by the JPEG's public path. */
export const SCREENSHOTS: Record<string, ScreenshotMeta> = {
  "/work/cadencestack/01-command-center.jpg": {
    "w": 1680,
    "h": 889,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cadencestack/02-content-pillars.jpg": {
    "w": 1680,
    "h": 887,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cadencestack/03-content-pipeline.jpg": {
    "w": 1680,
    "h": 886,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cadencestack/04-performance-analytics.jpg": {
    "w": 1680,
    "h": 887,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cadencestack/05-prompt-library.jpg": {
    "w": 1680,
    "h": 888,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cadencestack/06-repurpose-engine.jpg": {
    "w": 1680,
    "h": 886,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cadencestack/07-brand-voice.jpg": {
    "w": 1680,
    "h": 887,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cadencestack/08-post-database.jpg": {
    "w": 1680,
    "h": 890,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cadencestack/09-idea-bank.jpg": {
    "w": 1680,
    "h": 887,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/capitalcommand/01-overview.jpg": {
    "w": 1680,
    "h": 930,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/capitalcommand/02-portfolio.jpg": {
    "w": 1680,
    "h": 931,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/capitalcommand/03-markets.jpg": {
    "w": 1680,
    "h": 929,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/capitalcommand/04-ipo-intelligence.jpg": {
    "w": 1680,
    "h": 930,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/capitalcommand/05-signal-desk.jpg": {
    "w": 1680,
    "h": 928,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/capitalcommand/06-research-lab.jpg": {
    "w": 1680,
    "h": 926,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/capitalcommand/07-risk-center.jpg": {
    "w": 1680,
    "h": 927,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/capitalcommand/08-system-health.jpg": {
    "w": 1680,
    "h": 930,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/cgwalls/gallery.jpg": {
    "w": 1400,
    "h": 775,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/cgwalls/gallery2.jpg": {
    "w": 1400,
    "h": 775,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/cgwalls/hero.jpg": {
    "w": 1400,
    "h": 776,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/cgwalls/testimonials.jpg": {
    "w": 1400,
    "h": 773,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/sift/01-command-overview.jpg": {
    "w": 1680,
    "h": 926,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  },
  "/work/sift/02-tailor-resume.jpg": {
    "w": 1400,
    "h": 708,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/sift/03-cover-letter.jpg": {
    "w": 1400,
    "h": 709,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/sift/04-pipeline.jpg": {
    "w": 1400,
    "h": 713,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/sift/05-outreach.jpg": {
    "w": 1400,
    "h": 712,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/sift/06-funnel.jpg": {
    "w": 1400,
    "h": 707,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/sift/07-sources.jpg": {
    "w": 1400,
    "h": 712,
    "widths": [
      640,
      960,
      1280,
      1400
    ]
  },
  "/work/sift/08-command-insights.jpg": {
    "w": 1680,
    "h": 928,
    "widths": [
      640,
      960,
      1280,
      1680
    ]
  }
};
